- hosts: all
  roles:
    - base
    - dev
  vars:
      debian_user: arghya
      debian_codename: bookworm
      kitty_theme: Afterglow
 

- hosts: all
  become: true
  roles:
    - customize-gnome
  vars:
      gnome_user: arghya
      gnome_extensions:
        - id: 307
          enable: yes
        - id: 517
          enable: yes
        - id: 3088
          enable: yes
        - id: 19
          enable: yes
        - id: 744
          enable: yes
        - id: 8
          enable: yes
        - id: 1460
          enable: yes
        - id: 3724
          enable: yes
        - id: 3628
          enable: yes
        - id: 3193
          enable: yes
      gnome_gsettings:
        - schema: org.gnome.desktop.interface
          key: color-scheme
          value: prefer-dark
        - schema: org.gnome.shell.extensions.dash-to-dock
          key: click-action
          value: minimize-or-previews
        - schema: org.gnome.shell.extensions.dash-to-dock
          key: dock-position
          value: BOTTOM
