export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="powerlevel10k/powerlevel10k"
plugins=(
    git
    docker
    dotnet
    ubuntu
    vscode
    npm
    node
    nvm
    history
    zsh-autosuggestions
    zsh-syntax-highlighting
)


zstyle ':omz:update' mode auto      # update automatically without asking
zstyle ':omz:update' frequency 30
zstyle ':completion:*:*:docker:*' option-stacking yes
zstyle ':completion:*:*:docker-*:*' option-stacking yes

source $ZSH/oh-my-zsh.sh


export NVM_DIR="/home/arghya/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export DOTNET_ROOT=/home/arghya/.dotnet
export PATH=$PATH:$DOTNET_ROOT:$DOTNET_ROOT/tools

export TERM=xterm-256color
