  - name: Install APT apps
    apt:
      name:
        - build-essential
        - gnome-shell-extension-manager
        - snapd
        - flatpak
        - gnome-software-plugin-flatpak
        - htop
        - nvidia-driver
        - firmware-misc-nonfree
        - playonlinux
        - git
        - powerline
        - fonts-powerline
        - pipx
    become: true
  
  - name: Add Flathub Repository
    command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    become: true
  
  - name: Install Snap apps
    community.general.snap:
      name: "{{ item }}"
      classic: yes
    loop:
      - vlc
      - code
    become: true
  
  - name: Check if Google Chrome is installed and install if not
    block:
      - name: Check if Google Chrome is installed
        ansible.builtin.command: google-chrome --version
        register: chrome_version
        ignore_errors: true
      
      - name: Install Google Chrome
        apt:
          deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        when: chrome_version.rc != 0
    become: true

  - import_tasks: ufw.yml
    become: true

  - import_tasks: zsh.yml