  - name: Install APT apps
    apt:
      name:
        - kitty
    become: true
  
  - name: get kitty themes
    git:
      repo: https://github.com/dexpota/kitty-themes.git 
      dest: ~/.config/kitty/kitty-themes
      depth: 1
  
  - name: set kitty theme
    command: ln -sf ~/.config/kitty/kitty-themes/{{ kitty_theme }}.conf ~/.config/kitty/theme.conf
  
  - name: create new kitty.conf
    ansible.builtin.file:
      state: touch
      path: ~/.config/kitty/kitty.conf

  - name: add kitty theme config
    lineinfile:
      state: present
      path: "~/.config/kitty/kitty.conf"
      line: "include ./theme.conf"

  - name: set kitty as default
    alternatives:
      name: x-terminal-emulator
      path: /usr/bin/kitty
      priority: 50
      link: /usr/bin/x-terminal-emulator
    become: true
