---
# tasks file for base
- block:
  # - name: provide superuser rights to user
  #   become: true
  #   become_user: root
  #   become_method: su
  #   become_exe: su - 
  #   command: 'usermod -aG sudo {{ debian_user }}'
  
  - import_tasks: apt.yml
    become: true

  - name: uninstall gnome-games
    apt:
      name: gnome-games
      state: absent
      autoremove: yes
    become: true

  - import_tasks: essential-packages.yml
  
  - import_tasks: tlp.yml
    become: true

  - import_tasks: kitty.yml

  - import_tasks: theme.yml