---
- name: Update system and install software
  hosts: linux
  tasks:
    - name: System Update, Upgrade and Cleanup
      block:
        - name: Upgrade all packages to the latest version
          apt:
            update_cache: yes 
            upgrade: full

        - name: Cleanup Bloatware
          apt:
            name: gnome-games
            state: absent
            autoremove: yes
      become: yes
    
    - name: Configure Power Management
      block:
        - name: Remove power-profiles-daemont
          apt:
            name: power-profiles-daemon
            state: absent

        - name: Install TLP and related packages
          apt:
            name:
              - tlp
              - tlp-rdw
            state: present
        
        - name: Install TLPUI
          community.general.flatpak:
            name:
              - com.github.d4nj1.tlpui
            state: present

        - name: Start tlp
          command: tlp start
      become: yes
    
    - name: Install Essential Softwares
      block:
        - name: Install APT apps
          apt:
            name:
              - build-essential
              - gnome-shell-extension-manager
              - snapd
              - flatpak
              - gnome-software-plugin-flatpak
              - ufw
              - htop
              - nvidia-driver
              - firmware-misc-nonfree
              - playonlinux
              - zsh
              - git
    
        - name: Add Flathub Repository
          command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

        - name: Install Snap apps
          community.general.snap:
            name: "{{ item }}"
            classic: yes
          loop:
            - vlc
            - rider
            - intellij-idea-ultimate
            - webstorm
            - datagrip
            - code

        - name: Check if Google Chrome is installed and install if not
          block:
            - name: Check if Google Chrome is installed
              ansible.builtin.command: google-chrome --version
              register: chrome_version
              ignore_errors: yes

            - name: Download and install Google Chrome
              google_chrome_module:
                package_url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
              when: chrome_version.rc != 0
      become: yes
        
    - name: Development ENV Setup
      block:
        - name: Check if Oh My ZSH folder exists
          stat:
            path: /home/arghya/.oh-my-zsh
          register: oh_my_zsh_folder

        - name: Install Oh My ZSH
          shell: >
            curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh
          when: not oh_my_zsh_folder.stat.exists
        
        - name: Install nvm
          shell: >
              curl https://raw.githubusercontent.com/creationix/nvm/v0.7.0/install.sh | sh
              creates=/home/arghya/.nvm/nvm.sh
        
        - name: Update zshrc
          get_url:
            url: https://raw.githubusercontent.com/aGhosh02/ansible-playbooks/master/config/zshrc
            dest: ~/.zshrc  # Specify the destination path and filename
            force: yes     # Replace existing file if it exists
        
        - name: Update zprofile
          get_url:
            url: https://raw.githubusercontent.com/aGhosh02/ansible-playbooks/master/config/zprofile
            dest: ~/.zprofile # Specify the destination path and filename
            force: yes     # Replace existing file if it exists

        - name: Install Node
          zsh: nvm install --lts
        
        - name: Install DotNet
          dotnet_install:
            version: 6.0

        
      

    
